// Generated by gencpp from file delivery_navigation/ClientPose.msg
// DO NOT EDIT!


#ifndef DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSE_H
#define DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSE_H

#include <ros/service_traits.h>


#include <delivery_navigation/ClientPoseRequest.h>
#include <delivery_navigation/ClientPoseResponse.h>


namespace delivery_navigation
{

struct ClientPose
{

typedef ClientPoseRequest Request;
typedef ClientPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClientPose
} // namespace delivery_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delivery_navigation::ClientPose > {
  static const char* value()
  {
    return "52fafef8ad1674b735b9d3ff0ce96895";
  }

  static const char* value(const ::delivery_navigation::ClientPose&) { return value(); }
};

template<>
struct DataType< ::delivery_navigation::ClientPose > {
  static const char* value()
  {
    return "delivery_navigation/ClientPose";
  }

  static const char* value(const ::delivery_navigation::ClientPose&) { return value(); }
};


// service_traits::MD5Sum< ::delivery_navigation::ClientPoseRequest> should match
// service_traits::MD5Sum< ::delivery_navigation::ClientPose >
template<>
struct MD5Sum< ::delivery_navigation::ClientPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_navigation::ClientPose >::value();
  }
  static const char* value(const ::delivery_navigation::ClientPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_navigation::ClientPoseRequest> should match
// service_traits::DataType< ::delivery_navigation::ClientPose >
template<>
struct DataType< ::delivery_navigation::ClientPoseRequest>
{
  static const char* value()
  {
    return DataType< ::delivery_navigation::ClientPose >::value();
  }
  static const char* value(const ::delivery_navigation::ClientPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delivery_navigation::ClientPoseResponse> should match
// service_traits::MD5Sum< ::delivery_navigation::ClientPose >
template<>
struct MD5Sum< ::delivery_navigation::ClientPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_navigation::ClientPose >::value();
  }
  static const char* value(const ::delivery_navigation::ClientPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_navigation::ClientPoseResponse> should match
// service_traits::DataType< ::delivery_navigation::ClientPose >
template<>
struct DataType< ::delivery_navigation::ClientPoseResponse>
{
  static const char* value()
  {
    return DataType< ::delivery_navigation::ClientPose >::value();
  }
  static const char* value(const ::delivery_navigation::ClientPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSE_H
