// Generated by gencpp from file delivery_navigation/ClientPoseRequest.msg
// DO NOT EDIT!


#ifndef DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSEREQUEST_H
#define DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_navigation
{
template <class ContainerAllocator>
struct ClientPoseRequest_
{
  typedef ClientPoseRequest_<ContainerAllocator> Type;

  ClientPoseRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation(0.0)  {
    }
  ClientPoseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClientPoseRequest_

typedef ::delivery_navigation::ClientPoseRequest_<std::allocator<void> > ClientPoseRequest;

typedef boost::shared_ptr< ::delivery_navigation::ClientPoseRequest > ClientPoseRequestPtr;
typedef boost::shared_ptr< ::delivery_navigation::ClientPoseRequest const> ClientPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator1> & lhs, const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator1> & lhs, const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9cc91561ab081df3c838809b2058a1b";
  }

  static const char* value(const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9cc91561ab081dfULL;
  static const uint64_t static_value2 = 0x3c838809b2058a1bULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_navigation/ClientPoseRequest";
  }

  static const char* value(const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 orientation\n"
;
  }

  static const char* value(const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClientPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_navigation::ClientPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_navigation::ClientPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_NAVIGATION_MESSAGE_CLIENTPOSEREQUEST_H
